#!/bin/bash
cd /Users/bob/Projects/coding-puzzles/distributed-code-jam-2017-round-1/problem_A
/usr/bin/java -Djava.library.path=/Users/bob/Projects/coding-puzzles/distributed-code-jam-2017-practice-round/dcj_cli/dcj/../libraries:/Users/bob/Projects/coding-puzzles/distributed-code-jam-2017-round-1/problem_A -classpath /Users/bob/Projects/coding-puzzles/distributed-code-jam-2017-practice-round/dcj_cli/dcj/../libraries:/Users/bob/Projects/coding-puzzles/distributed-code-jam-2017-round-1/problem_A Wrapper
